export interface LabTest {
  id: string
  name: string
  shortName?: string
  labCompany: string
  sampleType: string
  category: string
  subcategory?: string
  price: number
  turnaroundDays: number
  description: string
  biomarkers: string[]
  popular?: boolean
  requiresFasting?: boolean
  homeCollection?: boolean
}

export const labTests: LabTest[] = [
  // Thyroid Tests
  {
    id: "1",
    name: "Comprehensive Thyroid Panel",
    shortName: "Thyroid Panel",
    labCompany: "Access Med Labs",
    sampleType: "Serum",
    category: "Thyroid",
    price: 89,
    turnaroundDays: 3,
    description: "Complete thyroid function assessment including TSH, Free T4, Free T3, and thyroid antibodies.",
    biomarkers: ["TSH", "Free T4", "Free T3", "TPO Antibodies", "Thyroglobulin Ab"],
    popular: true,
    requiresFasting: false,
    homeCollection: true,
  },
  {
    id: "2",
    name: "TSH",
    labCompany: "Access Med Labs",
    sampleType: "Serum",
    category: "Thyroid",
    price: 29,
    turnaroundDays: 2,
    description: "Thyroid-stimulating hormone test to evaluate thyroid function.",
    biomarkers: ["TSH"],
    popular: true,
    requiresFasting: false,
    homeCollection: true,
  },
  {
    id: "3",
    name: "Free T4",
    labCompany: "Access Med Labs",
    sampleType: "Serum",
    category: "Thyroid",
    price: 35,
    turnaroundDays: 2,
    description: "Measures unbound thyroxine hormone levels.",
    biomarkers: ["Free T4"],
    requiresFasting: false,
    homeCollection: true,
  },
  {
    id: "4",
    name: "Thyroid Peroxidase Antibodies",
    shortName: "TPO Antibodies",
    labCompany: "Diagnostic Solutions",
    sampleType: "Serum",
    category: "Thyroid",
    price: 45,
    turnaroundDays: 4,
    description: "Detects antibodies against thyroid peroxidase enzyme.",
    biomarkers: ["TPO Antibodies"],
    requiresFasting: false,
    homeCollection: true,
  },
  // Metabolic Tests
  {
    id: "5",
    name: "Comprehensive Metabolic Panel",
    shortName: "CMP",
    labCompany: "Access Med Labs",
    sampleType: "Serum",
    category: "Metabolic",
    price: 49,
    turnaroundDays: 2,
    description: "14-test panel measuring glucose, electrolytes, kidney and liver function.",
    biomarkers: [
      "Glucose",
      "BUN",
      "Creatinine",
      "Sodium",
      "Potassium",
      "Chloride",
      "CO2",
      "Calcium",
      "Total Protein",
      "Albumin",
      "Bilirubin",
      "Alkaline Phosphatase",
      "AST",
      "ALT",
    ],
    popular: true,
    requiresFasting: true,
    homeCollection: true,
  },
  {
    id: "6",
    name: "Hemoglobin A1c",
    shortName: "HbA1c",
    labCompany: "Access Med Labs",
    sampleType: "Whole Blood",
    category: "Metabolic",
    subcategory: "Diabetes",
    price: 39,
    turnaroundDays: 2,
    description: "Measures average blood sugar over the past 2-3 months.",
    biomarkers: ["Hemoglobin A1c"],
    popular: true,
    requiresFasting: false,
    homeCollection: true,
  },
  {
    id: "7",
    name: "Fasting Insulin",
    labCompany: "Access Med Labs",
    sampleType: "Serum",
    category: "Metabolic",
    subcategory: "Diabetes",
    price: 35,
    turnaroundDays: 2,
    description: "Measures insulin levels to assess insulin resistance.",
    biomarkers: ["Insulin"],
    requiresFasting: true,
    homeCollection: true,
  },
  {
    id: "8",
    name: "Fasting Glucose",
    labCompany: "Access Med Labs",
    sampleType: "Serum",
    category: "Metabolic",
    subcategory: "Diabetes",
    price: 15,
    turnaroundDays: 1,
    description: "Measures blood glucose levels after fasting.",
    biomarkers: ["Glucose"],
    popular: true,
    requiresFasting: true,
    homeCollection: true,
  },
  // Cardiovascular
  {
    id: "9",
    name: "Lipid Panel",
    labCompany: "Access Med Labs",
    sampleType: "Serum",
    category: "Cardiovascular",
    price: 45,
    turnaroundDays: 2,
    description: "Measures cholesterol levels including HDL, LDL, and triglycerides.",
    biomarkers: ["Total Cholesterol", "HDL", "LDL", "Triglycerides", "VLDL"],
    popular: true,
    requiresFasting: true,
    homeCollection: true,
  },
  {
    id: "10",
    name: "Advanced Lipid Panel",
    labCompany: "Diagnostic Solutions",
    sampleType: "Serum",
    category: "Cardiovascular",
    price: 129,
    turnaroundDays: 5,
    description: "Detailed cardiovascular risk assessment with particle size and number.",
    biomarkers: ["LDL Particle Number", "Small Dense LDL", "HDL Particle Number", "Lipoprotein(a)", "ApoB"],
    requiresFasting: true,
    homeCollection: true,
  },
  {
    id: "11",
    name: "High-Sensitivity CRP",
    shortName: "hs-CRP",
    labCompany: "Access Med Labs",
    sampleType: "Serum",
    category: "Cardiovascular",
    subcategory: "Inflammation",
    price: 35,
    turnaroundDays: 2,
    description: "Measures inflammation levels associated with cardiovascular risk.",
    biomarkers: ["hs-CRP"],
    requiresFasting: false,
    homeCollection: true,
  },
  // GI / Gut Health
  {
    id: "12",
    name: "GI-MAP",
    labCompany: "Diagnostic Solutions",
    sampleType: "Stool",
    category: "GI / Gut Health",
    price: 399,
    turnaroundDays: 14,
    description:
      "Comprehensive stool analysis using DNA technology to detect pathogens, bacteria, parasites, and digestive markers.",
    biomarkers: ["H. Pylori", "Parasites", "Bacteria", "Yeast", "Digestive Enzymes", "Gut Immunity"],
    popular: true,
    requiresFasting: false,
    homeCollection: true,
  },
  // Hormones
  {
    id: "13",
    name: "DUTCH Complete",
    labCompany: "Precision Analytical",
    sampleType: "Dried Urine",
    category: "Hormones",
    price: 399,
    turnaroundDays: 10,
    description: "Comprehensive hormone metabolite testing including cortisol, estrogen, progesterone, and androgens.",
    biomarkers: [
      "Cortisol",
      "Cortisone",
      "Estradiol",
      "Estrone",
      "Estriol",
      "Progesterone",
      "Testosterone",
      "DHEA-S",
      "Melatonin",
    ],
    popular: true,
    requiresFasting: false,
    homeCollection: true,
  },
  {
    id: "14",
    name: "Female Hormone Panel",
    labCompany: "Access Med Labs",
    sampleType: "Serum",
    category: "Hormones",
    subcategory: "Female Health",
    price: 149,
    turnaroundDays: 3,
    description: "Comprehensive female hormone assessment for fertility and cycle health.",
    biomarkers: ["Estradiol", "Progesterone", "FSH", "LH", "Prolactin", "DHEA-S"],
    requiresFasting: false,
    homeCollection: true,
  },
  {
    id: "15",
    name: "Testosterone, Free & Total",
    labCompany: "Access Med Labs",
    sampleType: "Serum",
    category: "Hormones",
    subcategory: "Male Health",
    price: 69,
    turnaroundDays: 3,
    description: "Measures both free and total testosterone levels.",
    biomarkers: ["Total Testosterone", "Free Testosterone", "SHBG"],
    popular: true,
    requiresFasting: false,
    homeCollection: true,
  },
  // Vitamins & Nutrients
  {
    id: "16",
    name: "Vitamin D, 25-Hydroxy",
    labCompany: "Access Med Labs",
    sampleType: "Serum",
    category: "Vitamins & Nutrients",
    price: 55,
    turnaroundDays: 3,
    description: "Measures vitamin D levels to assess deficiency or sufficiency.",
    biomarkers: ["25-Hydroxy Vitamin D"],
    popular: true,
    requiresFasting: false,
    homeCollection: true,
  },
  {
    id: "17",
    name: "Iron Panel",
    labCompany: "Access Med Labs",
    sampleType: "Serum",
    category: "Vitamins & Nutrients",
    price: 65,
    turnaroundDays: 2,
    description: "Comprehensive iron status assessment including ferritin and TIBC.",
    biomarkers: ["Iron", "Ferritin", "TIBC", "Iron Saturation"],
    requiresFasting: true,
    homeCollection: true,
  },
  {
    id: "18",
    name: "Vitamin B12 & Folate",
    labCompany: "Access Med Labs",
    sampleType: "Serum",
    category: "Vitamins & Nutrients",
    price: 59,
    turnaroundDays: 2,
    description: "Measures B12 and folate levels for energy and neurological health.",
    biomarkers: ["Vitamin B12", "Folate"],
    requiresFasting: false,
    homeCollection: true,
  },
  // Hematology
  {
    id: "19",
    name: "Complete Blood Count (CBC)",
    shortName: "CBC",
    labCompany: "Access Med Labs",
    sampleType: "Whole Blood",
    category: "Hematology",
    price: 25,
    turnaroundDays: 1,
    description: "Measures red blood cells, white blood cells, and platelets.",
    biomarkers: ["RBC", "WBC", "Hemoglobin", "Hematocrit", "Platelets", "MCV", "MCH", "MCHC"],
    popular: true,
    requiresFasting: false,
    homeCollection: true,
  },
  {
    id: "20",
    name: "CBC with Differential",
    labCompany: "Access Med Labs",
    sampleType: "Whole Blood",
    category: "Hematology",
    price: 35,
    turnaroundDays: 1,
    description: "CBC plus detailed white blood cell breakdown.",
    biomarkers: [
      "RBC",
      "WBC",
      "Hemoglobin",
      "Hematocrit",
      "Platelets",
      "Neutrophils",
      "Lymphocytes",
      "Monocytes",
      "Eosinophils",
      "Basophils",
    ],
    requiresFasting: false,
    homeCollection: true,
  },
  // Metabolic
  {
    id: "21",
    name: "Basic Metabolic Panel",
    shortName: "BMP",
    labCompany: "Access Med Labs",
    sampleType: "Serum",
    category: "Metabolic",
    price: 35,
    turnaroundDays: 1,
    description: "8-test panel for kidney function and electrolytes.",
    biomarkers: ["Glucose", "BUN", "Creatinine", "Sodium", "Potassium", "Chloride", "CO2", "Calcium"],
    popular: true,
    requiresFasting: true,
    homeCollection: true,
  },
  // Liver
  {
    id: "22",
    name: "Liver Function Panel",
    labCompany: "Access Med Labs",
    sampleType: "Serum",
    category: "Liver",
    price: 45,
    turnaroundDays: 2,
    description: "Comprehensive liver enzyme and function assessment.",
    biomarkers: ["AST", "ALT", "ALP", "GGT", "Bilirubin", "Albumin", "Total Protein"],
    requiresFasting: false,
    homeCollection: true,
  },
  // Allergy & Immunity
  {
    id: "23",
    name: "Food Sensitivity Panel",
    labCompany: "Diagnostic Solutions",
    sampleType: "Serum",
    category: "Allergy & Immunity",
    price: 299,
    turnaroundDays: 10,
    description: "Tests for IgG reactions to 96 common foods.",
    biomarkers: ["96 Food IgG Antibodies"],
    requiresFasting: false,
    homeCollection: true,
  },
  {
    id: "24",
    name: "Environmental Allergy Panel",
    labCompany: "Diagnostic Solutions",
    sampleType: "Serum",
    category: "Allergy & Immunity",
    price: 199,
    turnaroundDays: 7,
    description: "Tests for IgE reactions to common environmental allergens.",
    biomarkers: ["Dust Mites", "Mold", "Pollen", "Pet Dander", "Grasses"],
    requiresFasting: false,
    homeCollection: true,
  },
]

export const categories = Array.from(new Set(labTests.map((t) => t.category)))
export const labCompanies = Array.from(new Set(labTests.map((t) => t.labCompany)))
export const sampleTypes = Array.from(new Set(labTests.map((t) => t.sampleType)))
